### ISSUE TITLE
Running the example using ghc or emac.

### ISSUE THREAD

**Issue by rdtor** [Euterpea/Euterpea2-Examples#1]
Hi, it is offrelated topic to the repo so feel free to close the issue. I been trying to run the demo examples by using ghc example.ghc inside the directory it says  compile ok and one module loaded, but there is no sound. And what is the command to execute the program using emacs in haskell mode?

**Comment by donya** [comment]
The examples are meant to be loaded from GHCi and used interactively, not compiled with GHC. To run a command, just type it into the interpreter. Signal-level examples will produce WAV files when executed (no sound playback). If you want to compile with GHC, you need to write a main function with type IO(). 

For debugging MIDI playback, first test whether this command:

play $ c 4 qn

produces sound in GHCi. If it does, you can simply use "play x" where x is the name of the Music value you want to play. If you have no sound from the command above, check the instructions for your OS here:
http://www.euterpea.com/euterpea/setting-up-midi/
On Mac/Linux, make sure you have a synthesizer running before starting the program or opening GHCi and then check the device numbers with the "devices" function in GHCi (you may need to use "playDev" instead of "play"). 

I don't use Emac and so don't know the Haskell-related commands offhand.

**Comment by rdtor** [comment]
Thank you i managed to setup atom with haskell and it works flawlessly also
all the examples.
